# Generated by Django 4.2.13 on 2024-12-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.SlugField(unique=True),
        ),
    ]
