# Generated by Django 4.2.13 on 2024-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title_full',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
